<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'OmniUser\Module'                        => __DIR__ . '/Module.php',
    'OmniUser\Controller\UserControllerController' => __DIR__ . '/src/OmniUser/Controller/UserControllerController.php',
    'OmniUserTest\Framework\TestCase'        => __DIR__ . '/tests/OmniUser/Framework/TestCase.php',
    'OmniUserTest\SampleTest'                => __DIR__ . '/tests/OmniUser/SampleTest.php',
);
