<strong>Module:</strong>        OmniBlog &raquo;
<strong>Controller:</strong>    Category &raquo;
<strong>Action:</strong>        edit
<?php

$title = 'Edit Category';
$this->headTitle($title);

$route = 'omni-blog/blogchild';
$controller = 'category';

$urlEdit = $this->url($route, array(
    'controller' => $controller, 
    'action' => 'edit', 
    'id' => $this->id)
    );
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php

$form->setAttribute('action', $urlEdit);
//$form->setAttribute('id', $this->id);
$form->prepare();

echo $this->form()->openTag($form);

// //Get bound element
// $category = $form->get('category');
// echo $this->formHidden($category->get('id'));
// echo $this->formRow($category->get('title'));

// echo $this->formHidden($form->get('csrf'));
// echo $this->formElement($form->get('submit'));
echo $this->formCollection($form);

echo $this->form()->closeTag();
