<?php
$title = 'Blog';
$this->headTitle($title);

$route = 'omni-blog/blogchild';
$controller = 'category'; //current controller
?>

<div class="page_content">
    <h1 class="title">Blog</h1>
    <p><a href="https://github.com/Suiko6272/Website/">Website's GitHub Repo</a><br>This is a simple Blog CMS developed in Zend Framework 2.<br>In active development so styles may break or not even exist.<br>Below are the latest three posts and existing categories.</br></p>
    <div class="blog_posts">
        <h2>Latest Posts</h2>
        <?php 
            //print_r($associations);
            foreach ($latestPosts as $post):
            $post_id = $post->getId();
        ?>
            <div style="padding:10px;display:block">
            <div style="padding:inherit;background-color:#F2F2F2;display:inline-block" class ="post" id="post-<?php echo $this->escapehtml($post_id);?>">
                <h3><a href="<?php echo $this->url($route, 
                            array('controller' => 'post',
                            'action'=>'view', 'id' => $post_id
                            )); ?>">
                    <?php echo $post->getTitle();?>
                </a></h3>
                <p class="shorthand"><?php echo $this->escapehtml($post->getContent());?></p>
                <!-- <p class="author" >Posted By: <?php echo $this->escapehtml($post->getAuthor());?></p> -->
            </div><!-- post -->
            </div>
        <?php endforeach; ?>
    </div><!-- blog_posts -->
    <div class="categories">
        <h2>Categories</h2>
        <?php foreach ($categories as $cat) : ?>
            <p>#<a href="<?php echo $this->url($route, array(
            'controller' => $controller,
            'action'=>'view',
            'id' => $cat->getId()
        ));
        ?>"><?php echo $this->escapeHtml($cat->getTitle());?></a></p>
        <?php endforeach; ?>
    </div>
</div><!-- page_content -->