<table>
    <tr>
        <th>Page Links</th>
    </tr>
    <tr>
        <td><a href="user">User</a></td>
    </tr>
    <tr>
        <td></td>
        <td>
            <table>
                <tr>
                    <td><a href="user/login">Login</a></td>
                </tr>
                <tr>
                    <td><a href="user/register">Register</a></td>
                </tr>
                <tr>
                    <td><a href="user/changeemail">Change Email</a></td>
                </tr>
                <tr>
                    <td><a href="user/chagnepassword">Change Password</a></td>
                </tr>
            </table>
        </td>
    </tr>
    <tr>
        <td><a href="blog">Blog</a></td>
    </tr>
    <tr>
        <td></td>
        <td>
            <table>
                <tr>
                    <td><a href="blog/category">Category</a></td>
                </tr>
                <tr>
                    <td></td>
                    <td>
                        <table>
                            <tr>
                                <td><a href="blog/category/add">Add</a></td>
                            </tr>
                        </table>
                    </td>
                </tr>
                <tr>
                    <td><a href="blog/post">Post</a></td>
                </tr>
                <tr>
                    <td></td>
                    <td>
                        <table>
                            <tr>
                                <td><a href="blog/post/add">Add</a></td>
                            </tr>
                        </table>
                    </td>
                </tr>
            </table>
        </td>
    </tr>
</table>