<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'OmniBlog\Module'                        => __DIR__ . '/Module.php',
    'OmniBlog\Controller\PostController' => __DIR__ . '/src/OmniBlog/Controller/PostController.php',
    'OmniBlog\Controller\CommentController' => __DIR__ . '/src/OmniBlog/Controller/CommentController.php',
    'OmniBlog\Controller\CategoryController' => __DIR__ . '/src/OmniBlog/Controller/CategoryController.php',
    'OmniBlogTest\Framework\TestCase'        => __DIR__ . '/tests/OmniBlog/Framework/TestCase.php',
    'OmniBlogTest\SampleTest'                => __DIR__ . '/tests/OmniBlog/SampleTest.php',
);
